# Generated by Django 3.2.5 on 2021-07-06 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 13, 51, 3, 775534), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 13, 51, 3, 776535), verbose_name='last login'),
        ),
    ]
